# Generated by Django 2.0.7 on 2018-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180803_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('training', '培训机构'), ('college', '高校'), ('person', '个人')], default='training', max_length=20, verbose_name='机构类别'),
        ),
    ]
