# Generated by Django 2.0.7 on 2018-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '课程章节', 'verbose_name_plural': '课程章节'},
        ),
        migrations.AlterField(
            model_name='course',
            name='click_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='学习人数'),
        ),
    ]
